/* ==========================================================================
   PROJECT   : Artesanias y Textiles Mayas, S.A. - Web System
   PHASE     : Phase 3 (P3) - Oracle Database, E-commerce & Accounting
   MODULE    : Inventory, Sales and Accounting
   ENGINE    : Oracle Database 12c or higher (uses IDENTITY columns)
   AUTHOR    : Alan Cortez - DBA & Backend Engineer
   ========================================================================== */

-- ==========================================================================
-- 0. (OPTIONAL) CLEAN START - drop objects if they already exist
-- ==========================================================================
-- Uncomment if you need to rebuild the schema from scratch.
/*
DROP TABLE payments PURGE;
DROP TABLE journal_entry_details PURGE;
DROP TABLE journal_entries PURGE;
DROP TABLE chart_of_accounts PURGE;
DROP TABLE invoices PURGE;
DROP TABLE sales_order_details PURGE;
DROP TABLE sales_orders PURGE;
DROP TABLE customers PURGE;
DROP TABLE inventory_movements PURGE;
DROP TABLE products PURGE;
DROP TABLE artisans PURGE;
DROP TABLE categories PURGE;
*/

-- ==========================================================================
-- 1. INVENTORY MODULE
-- ==========================================================================

CREATE TABLE categories (
    category_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name   VARCHAR2(100)  NOT NULL,
    description     VARCHAR2(255)
);

CREATE TABLE artisans (
    artisan_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name         VARCHAR2(150) NOT NULL,
    cooperative_name  VARCHAR2(150),
    region            VARCHAR2(100),
    phone             VARCHAR2(20),
    email             VARCHAR2(100)
);

CREATE TABLE products (
    product_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name     VARCHAR2(150)  NOT NULL,
    description      VARCHAR2(500),
    category_id      NUMBER         NOT NULL,
    artisan_id       NUMBER,
    unit_price       NUMBER(10,2)   NOT NULL,
    unit_cost        NUMBER(10,2),
    stock_quantity   NUMBER         DEFAULT 0 NOT NULL,
    reorder_level    NUMBER         DEFAULT 5,
    unit_of_measure  VARCHAR2(20)   DEFAULT 'UNIT',
    product_status   VARCHAR2(20)   DEFAULT 'ACTIVE',
    created_at       DATE           DEFAULT SYSDATE,
    CONSTRAINT fk_products_category FOREIGN KEY (category_id) REFERENCES categories(category_id),
    CONSTRAINT fk_products_artisan  FOREIGN KEY (artisan_id)  REFERENCES artisans(artisan_id),
    CONSTRAINT ck_products_price    CHECK (unit_price >= 0),
    CONSTRAINT ck_products_stock    CHECK (stock_quantity >= 0),
    CONSTRAINT ck_products_status   CHECK (product_status IN ('ACTIVE','INACTIVE'))
);

CREATE TABLE inventory_movements (
    movement_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id      NUMBER        NOT NULL,
    movement_type   VARCHAR2(10)  NOT NULL,
    quantity        NUMBER        NOT NULL,
    movement_date   DATE          DEFAULT SYSDATE,
    reference_note  VARCHAR2(255),
    CONSTRAINT fk_movements_product FOREIGN KEY (product_id) REFERENCES products(product_id),
    CONSTRAINT ck_movements_type    CHECK (movement_type IN ('IN','OUT')),
    CONSTRAINT ck_movements_qty     CHECK (quantity > 0)
);

-- ==========================================================================
-- 2. SALES MODULE
-- ==========================================================================

CREATE TABLE customers (
    customer_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name       VARCHAR2(150) NOT NULL,
    email           VARCHAR2(100) UNIQUE,
    phone           VARCHAR2(20),
    address         VARCHAR2(255),
    country         VARCHAR2(100),
    customer_type   VARCHAR2(20)  DEFAULT 'NATIONAL',
    CONSTRAINT ck_customers_type CHECK (customer_type IN ('NATIONAL','INTERNATIONAL'))
);

CREATE TABLE sales_orders (
    order_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id   NUMBER       NOT NULL,
    order_date    DATE         DEFAULT SYSDATE,
    order_status  VARCHAR2(20) DEFAULT 'PENDING',
    subtotal      NUMBER(12,2) DEFAULT 0,
    iva_amount    NUMBER(12,2) DEFAULT 0,
    total_amount  NUMBER(12,2) DEFAULT 0,
    CONSTRAINT fk_orders_customer FOREIGN KEY (customer_id) REFERENCES customers(customer_id),
    CONSTRAINT ck_orders_status   CHECK (order_status IN ('PENDING','CONFIRMED','SHIPPED','CANCELLED'))
);

CREATE TABLE sales_order_details (
    detail_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id       NUMBER       NOT NULL,
    product_id     NUMBER       NOT NULL,
    quantity       NUMBER       NOT NULL,
    unit_price     NUMBER(10,2) NOT NULL,
    line_subtotal  NUMBER(12,2),
    CONSTRAINT fk_details_order   FOREIGN KEY (order_id)   REFERENCES sales_orders(order_id),
    CONSTRAINT fk_details_product FOREIGN KEY (product_id) REFERENCES products(product_id),
    CONSTRAINT ck_details_qty     CHECK (quantity > 0)
);

-- ==========================================================================
-- 3. ACCOUNTING MODULE
-- ==========================================================================

CREATE TABLE invoices (
    invoice_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id        NUMBER        NOT NULL UNIQUE,
    invoice_number  VARCHAR2(30)  UNIQUE NOT NULL,
    invoice_date    DATE          DEFAULT SYSDATE,
    subtotal        NUMBER(12,2)  NOT NULL,
    iva_amount      NUMBER(12,2)  NOT NULL,
    total_amount    NUMBER(12,2)  NOT NULL,
    CONSTRAINT fk_invoices_order FOREIGN KEY (order_id) REFERENCES sales_orders(order_id)
);

CREATE TABLE chart_of_accounts (
    account_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_code  VARCHAR2(20)  UNIQUE NOT NULL,
    account_name  VARCHAR2(150) NOT NULL,
    account_type  VARCHAR2(20)  NOT NULL,
    CONSTRAINT ck_accounts_type CHECK (account_type IN ('ASSET','LIABILITY','EQUITY','INCOME','EXPENSE'))
);

CREATE TABLE journal_entries (
    entry_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_date     DATE          DEFAULT SYSDATE,
    description    VARCHAR2(255),
    reference_doc  VARCHAR2(50)
);

CREATE TABLE journal_entry_details (
    entry_detail_id  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_id         NUMBER       NOT NULL,
    account_id       NUMBER       NOT NULL,
    debit_amount     NUMBER(12,2) DEFAULT 0,
    credit_amount    NUMBER(12,2) DEFAULT 0,
    CONSTRAINT fk_jed_entry   FOREIGN KEY (entry_id)   REFERENCES journal_entries(entry_id),
    CONSTRAINT fk_jed_account FOREIGN KEY (account_id) REFERENCES chart_of_accounts(account_id)
);

CREATE TABLE payments (
    payment_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id      NUMBER       NOT NULL,
    payment_date    DATE         DEFAULT SYSDATE,
    amount          NUMBER(12,2) NOT NULL,
    payment_method  VARCHAR2(30) NOT NULL,
    CONSTRAINT fk_payments_invoice FOREIGN KEY (invoice_id) REFERENCES invoices(invoice_id),
    CONSTRAINT ck_payments_method  CHECK (payment_method IN ('CASH','CREDIT_CARD','BANK_TRANSFER','PAYPAL'))
);

-- ==========================================================================
-- 4. INDEXES (Oracle does NOT auto-index foreign keys, unlike primary keys)
-- ==========================================================================

CREATE INDEX ix_products_category   ON products(category_id);
CREATE INDEX ix_products_artisan    ON products(artisan_id);
CREATE INDEX ix_movements_product   ON inventory_movements(product_id);
CREATE INDEX ix_movements_date      ON inventory_movements(movement_date);
CREATE INDEX ix_orders_customer     ON sales_orders(customer_id);
CREATE INDEX ix_orders_date         ON sales_orders(order_date);
CREATE INDEX ix_details_order       ON sales_order_details(order_id);
CREATE INDEX ix_details_product     ON sales_order_details(product_id);
CREATE INDEX ix_invoices_order      ON invoices(order_id);
CREATE INDEX ix_jed_entry           ON journal_entry_details(entry_id);
CREATE INDEX ix_jed_account         ON journal_entry_details(account_id);
CREATE INDEX ix_payments_invoice    ON payments(invoice_id);

-- ==========================================================================
-- 5. FUNCTIONS
-- ==========================================================================

-- Guatemala IVA rate = 12%
CREATE OR REPLACE FUNCTION fn_calculate_iva (
    p_subtotal IN NUMBER
) RETURN NUMBER
IS
    c_iva_rate CONSTANT NUMBER := 0.12;
BEGIN
    RETURN ROUND(p_subtotal * c_iva_rate, 2);
END fn_calculate_iva;
/

-- ==========================================================================
-- 6. STORED PROCEDURES
-- ==========================================================================

-- 6.1 Recalculates subtotal, IVA and total for a sales order,
--     based on its detail lines.
CREATE OR REPLACE PROCEDURE sp_calculate_order_totals (
    p_order_id IN NUMBER
)
IS
    v_subtotal NUMBER(12,2);
    v_iva      NUMBER(12,2);
BEGIN
    SELECT NVL(SUM(quantity * unit_price), 0)
    INTO   v_subtotal
    FROM   sales_order_details
    WHERE  order_id = p_order_id;

    v_iva := fn_calculate_iva(v_subtotal);

    UPDATE sales_orders
    SET    subtotal     = v_subtotal,
           iva_amount   = v_iva,
           total_amount = v_subtotal + v_iva
    WHERE  order_id = p_order_id;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20001, 'Error calculating order totals: ' || SQLERRM);
END sp_calculate_order_totals;
/

-- 6.2 Generates an invoice from a confirmed sales order.
CREATE OR REPLACE PROCEDURE sp_generate_invoice (
    p_order_id IN NUMBER
)
IS
    v_subtotal NUMBER(12,2);
    v_iva      NUMBER(12,2);
    v_total    NUMBER(12,2);
    v_invoice_number VARCHAR2(30);
BEGIN
    sp_calculate_order_totals(p_order_id);

    SELECT subtotal, iva_amount, total_amount
    INTO   v_subtotal, v_iva, v_total
    FROM   sales_orders
    WHERE  order_id = p_order_id;

    v_invoice_number := 'INV-' || TO_CHAR(SYSDATE, 'YYYYMMDD') || '-' || p_order_id;

    INSERT INTO invoices (order_id, invoice_number, invoice_date, subtotal, iva_amount, total_amount)
    VALUES (p_order_id, v_invoice_number, SYSDATE, v_subtotal, v_iva, v_total);

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20002, 'Error generating invoice: ' || SQLERRM);
END sp_generate_invoice;
/

-- 6.3 Sales report between two dates, grouped by product.
--     Returns an open cursor (REF CURSOR) to be consumed by the app layer.
CREATE OR REPLACE PROCEDURE sp_sales_report (
    p_start_date IN DATE,
    p_end_date   IN DATE,
    p_cursor     OUT SYS_REFCURSOR
)
IS
BEGIN
    OPEN p_cursor FOR
        SELECT p.product_id,
               p.product_name,
               c.category_name,
               SUM(d.quantity)               AS units_sold,
               SUM(d.quantity * d.unit_price) AS total_sales
        FROM   sales_order_details d
        JOIN   sales_orders o   ON o.order_id = d.order_id
        JOIN   products p       ON p.product_id = d.product_id
        JOIN   categories c     ON c.category_id = p.category_id
        WHERE  o.order_date BETWEEN p_start_date AND p_end_date
        AND    o.order_status <> 'CANCELLED'
        GROUP BY p.product_id, p.product_name, c.category_name
        ORDER BY total_sales DESC;
END sp_sales_report;
/

-- 6.4 Accounting trial balance (sum of debits/credits per account).
CREATE OR REPLACE PROCEDURE sp_trial_balance (
    p_cursor OUT SYS_REFCURSOR
)
IS
BEGIN
    OPEN p_cursor FOR
        SELECT a.account_code,
               a.account_name,
               a.account_type,
               NVL(SUM(d.debit_amount), 0)  AS total_debit,
               NVL(SUM(d.credit_amount), 0) AS total_credit,
               NVL(SUM(d.debit_amount), 0) - NVL(SUM(d.credit_amount), 0) AS balance
        FROM   chart_of_accounts a
        LEFT JOIN journal_entry_details d ON d.account_id = a.account_id
        GROUP BY a.account_code, a.account_name, a.account_type
        ORDER BY a.account_code;
END sp_trial_balance;
/

-- ==========================================================================
-- 7. ACCOUNTING / SALES QUERIES (examples for reports)
-- ==========================================================================

-- 7.1 Total sales by month
-- SELECT TO_CHAR(order_date,'YYYY-MM') AS sales_month,
--        SUM(total_amount) AS monthly_total
-- FROM   sales_orders
-- WHERE  order_status <> 'CANCELLED'
-- GROUP BY TO_CHAR(order_date,'YYYY-MM')
-- ORDER BY sales_month;

-- 7.2 IVA collected per month (accounting/tax report)
-- SELECT TO_CHAR(order_date,'YYYY-MM') AS period,
--        SUM(iva_amount) AS iva_collected
-- FROM   sales_orders
-- WHERE  order_status <> 'CANCELLED'
-- GROUP BY TO_CHAR(order_date,'YYYY-MM')
-- ORDER BY period;

-- 7.3 Top selling artisans/cooperatives
-- SELECT ar.full_name, ar.cooperative_name, SUM(d.quantity*d.unit_price) AS revenue
-- FROM   sales_order_details d
-- JOIN   products p ON p.product_id = d.product_id
-- JOIN   artisans ar ON ar.artisan_id = p.artisan_id
-- GROUP BY ar.full_name, ar.cooperative_name
-- ORDER BY revenue DESC;

-- 7.4 Products below reorder level (inventory alert)
-- SELECT product_id, product_name, stock_quantity, reorder_level
-- FROM   products
-- WHERE  stock_quantity <= reorder_level
-- AND    product_status = 'ACTIVE';

-- ==========================================================================
-- 8. EXAMPLE EXECUTION (manual test block)
-- ==========================================================================
/*
BEGIN
    sp_calculate_order_totals(1);
    sp_generate_invoice(1);
END;
/

VARIABLE rc REFCURSOR;
EXEC sp_sales_report(DATE '2026-01-01', DATE '2026-12-31', :rc);
PRINT rc;
*/
